services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped

  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017
      - JWT_SECRET=secret

  frontend:
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    container_name: frontend
    ports:
      - "8080:3000"