services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: backend/backend.dockerfile
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017
      - JWT_SECRET=secret
    ports:
      - "3000:3000"
