services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    restart: unless-stopped


  folium:
    image: folium:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: folium
    ports:
      - "1234:1234"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - ./data:/data/db
    restart: always