services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    restart: unless-stopped

  folium:
    image: folium:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: folium
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - ./backend/images:/app/images
      - ./backend/html:/app/html
      - ./backend/public:/app/src/public
    restart: always