services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./db:/data/db
    restart: unless-stopped


  folium:
    image: ghcr.io/dcontt00/folium:latest
    container_name: folium
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - ./folium_data/images:/app/images
      - ./folium_data/html:/app/html
      - ./folium_data/public:/app/src/public
    restart: always