export default interface IComponentClass {
    _id: string;
    __t: string; // Type of component
    componentId: number; // Autogenerated ID
    index: number;
    parent_id: string;

    toHtml(): string;
}