import {Document} from "mongoose"


export default interface IComponent extends Document {
    _id: string;
    __t: string; // Type of component
    componentId: number; // Autogenerated ID
    index: number;
    parent_id: string;
}