export default interface Component {
    _id: string | null;
    __t: string; // Type of component
    componentId: number; // Autogenerated ID
    index: number;
    parent_id: string;
    className: string
}