name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:



jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install
        working-directory: ./backend

      - name: Run Jest tests
        env:
          MONGO_URI: mongodb://localhost:27017/test
        run: yarn test
        working-directory: ./backend

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg GH_OAUTH_CLIENT_ID=${{ secrets.GH_OAUTH_CLIENT_ID }} \
            --build-arg GH_OAUTH_CLIENT_SECRET=${{ secrets.GH_OAUTH_CLIENT_SECRET }} \
            -t ghcr.io/${{ github.repository_owner }}/folium:latest .

      # Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/folium:latest